---
# ejemplo2-cron-avanzado.yml (corregido)
# Este playbook muestra características avanzadas del módulo cron

- name: Gestión avanzada de tareas cron
  hosts: all
  become: yes
  
  tasks:
    - name: Crear usuario para tareas programadas
      user:
        name: cronuser
        comment: "Usuario para tareas cron"
        shell: /bin/bash
        state: present
        
    - name: Crear directorio para logs
      file:
        path: /var/log/cron-tasks
        state: directory
        owner: cronuser
        group: cronuser
        mode: '0755'
        
    - name: Establecer tarea cron con variables de entorno
      cron:
        name: "Backup semanal"
        user: cronuser
        weekday: "0"    # Domingo
        hour: "3"
        minute: "30"
        job: "BACKUP_OPTS='--compress --exclude-vcs' LOG_LEVEL='info' /usr/local/scripts/backup.sh /home /backup"
        cron_file: weekly-backup
        state: present
        
    - name: Añadir tarea con expresión crontab completa
      cron:
        name: "Monitoreo de recursos"
        user: cronuser
        cron_file: monitoring
        job: "/usr/local/scripts/monitor-resources.sh > /var/log/cron-tasks/monitor.log 2>&1"
        minute: "*/15"    # Cada 15 minutos
        state: present
        
    - name: Eliminar tarea antigua que ya no es necesaria
      cron:
        name: "Tarea obsoleta"
        state: absent
